services:
  # server:
  #   build:
  #     context: .
  #     target: builder
  #     args:
  #       - WATCH=1
  #   restart: unless-stopped
  #   command:
  #     - bash
  #     - -c
  #     - |
  #       cargo watch -s 'cargo run --profile dev --bin server'
  #   volumes:
  #     - ./server:/app/server
  #     - ./shared:/app/shared
  #     - ./src:/app/src
  #     - ./tests:/app/tests
  #   env_file:
  #     - .env
  #     - .env.server
  #   ports:
  #     - ${PORT}:${PORT}
  #   healthcheck:
  #     test: ["CMD", "nc", "-zv", "127.0.0.1", "${PORT}"]
  #     interval: 2s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 3s

  worker:
    build:
      context: .
      target: builder
      args:
        - WATCH=1
    restart: unless-stopped
    deploy:
      replicas: 1
    network_mode: host
    command:
      - bash
      - -c
      - |
        cargo watch -s 'cargo run --profile dev --bin worker'
    volumes:
      - ./worker:/app/worker
      - ./shared:/app/shared
      - ./src:/app/src
      - ./tests:/app/tests
    env_file:
      - .env
      - .env.worker
    # depends_on:
    #   server:
    #       condition: service_healthy

